version: "3"

networks:
  trade-network:
    external: true

volumes:
  postgres:
    driver: local

services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - trade-network
  
  postgres:
    image: postgres:13.3
    container_name: postgres
    environment: 
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432" 
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - trade-network
    
    